apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-label
 
spec:
  selector:
    matchLabels:
      app: nginx-label
 
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - mountPath: /mydata-container
              name: my-hostpath-volume
      volumes:
        - name: my-hostpath-volume
          hostPath:
            path: /home/scwallis2020/data

