apiVersion: apps/v1beta #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: velero
spec:
  serviceName: minio
  replicas: 4
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-storage-claim
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY                  ## velero 연동 시 사용되는 정보
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:latest
        args:
        - server 
        - http://minio-{0...3}.minio.velero.svc.cluster.local/data   # 4대의 분산 노드와 통신하기 위한 service 내부 도메인 / 도메인 뒤에 url 경로는 volume 매핑되는 폴더 경로
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
